// /*
//  * Ntsctsf_QoSandTSCAssistance Service API
//  *
//  * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
//  *
//  * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3.
//  * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
//  *
//  * API version: 1.1.0-alpha.4
//  * Generated by: OpenAPI Generator (https://openapi-generator.tech)
//  */

// package QoSandTSCAssistance

// import (
// 	"github.com/free5gc/openapi"
// 	"github.com/free5gc/openapi/models"

// 	"context"
// 	"io"
// 	"net/url"
// 	"strings"
// )

// // Linger please
// var (
// 	_ context.Context
// )

// type EventsSubscriptionDocumentApiService service

// /*
//  EventsSubscriptionDocumentApiService Deletes the Events Subscription subresource.
//   * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
//   * @param AppSessionId - String identifying the Individual TSC Application Session Context resource

//  @return DeleteEventsSubscResponse
// */

// // DeleteEventsSubscRequest
// type DeleteEventsSubscRequest struct {
// 	AppSessionId *string
// }

// func (r *DeleteEventsSubscRequest) SetAppSessionId(AppSessionId string) {
// 	r.AppSessionId = &AppSessionId
// }

// type DeleteEventsSubscResponse struct {
// }

// type DeleteEventsSubscError struct {
// 	Location             string
// 	Var3gppSbiTargetNfId string
// 	ProblemDetails       *models.ProblemDetails
// 	RedirectResponse     *models.RedirectResponse
// }

// func (a *EventsSubscriptionDocumentApiService) DeleteEventsSubsc(ctx context.Context, request *DeleteEventsSubscRequest) (*DeleteEventsSubscResponse, error) {
// 	var (
// 		localVarHTTPMethod   = strings.ToUpper("Delete")
// 		localVarPostBody     interface{}
// 		localVarFormFileName string
// 		localVarFileName     string
// 		localVarFileBytes    []byte
// 		localVarReturnValue  DeleteEventsSubscResponse
// 	)

// 	// create path and map variables
// 	localVarPath := a.client.cfg.BasePath() + "/tsc-app-sessions/{appSessionId}/events-subscription"
// 	localVarPath = strings.Replace(localVarPath, "{"+"appSessionId"+"}", openapi.StringOfValue(*request.AppSessionId), -1)

// 	localVarHeaderParams := make(map[string]string)
// 	localVarQueryParams := url.Values{}
// 	localVarFormParams := url.Values{}

// 	localVarHTTPContentTypes := []string{"application/json"}

// 	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

// 	// to determine the Accept header
// 	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

// 	// set Accept header
// 	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
// 	if localVarHTTPHeaderAccept != "" {
// 		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
// 	}

// 	r, err := openapi.PrepareRequest(ctx, a.client.cfg, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
// 	if err != nil {
// 		return nil, err
// 	}

// 	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
// 	if err != nil || localVarHTTPResponse == nil {
// 		return nil, err
// 	}

// 	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
// 	if err != nil {
// 		return nil, err
// 	}
// 	err = localVarHTTPResponse.Body.Close()
// 	if err != nil {
// 		return nil, err
// 	}

// 	apiError := openapi.GenericOpenAPIError{
// 		RawBody:     localVarBody,
// 		ErrorStatus: localVarHTTPResponse.StatusCode,
// 	}

// 	switch localVarHTTPResponse.StatusCode {
// 	case 204:
// 		return &localVarReturnValue, nil
// 	case 307:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 308:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 400:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 401:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 403:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 404:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 429:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 500:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 502:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 503:
// 		var v DeleteEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	default:
// 		return nil, apiError
// 	}
// }

// /*
//  EventsSubscriptionDocumentApiService Creates or modifies an Events Subscription subresource
//   * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
//   * @param AppSessionId - String identifying the Events Subscription resource
//   * @param EventsSubscReqData - Creation or modification of an Events Subscription resource.

//  @return PutEventsSubscResponse
// */

// // PutEventsSubscRequest
// type PutEventsSubscRequest struct {
// 	AppSessionId       *string
// 	EventsSubscReqData *models.EventsSubscReqData
// }

// func (r *PutEventsSubscRequest) SetAppSessionId(AppSessionId string) {
// 	r.AppSessionId = &AppSessionId
// }
// func (r *PutEventsSubscRequest) SetEventsSubscReqData(EventsSubscReqData models.EventsSubscReqData) {
// 	r.EventsSubscReqData = &EventsSubscReqData
// }

// type PutEventsSubscResponse struct {
// 	Location           string
// 	EventsSubscReqData *models.EventsSubscReqData
// }

// type PutEventsSubscError struct {
// 	Location             string
// 	Var3gppSbiTargetNfId string
// 	ProblemDetails       *models.ProblemDetails
// 	RedirectResponse     *models.RedirectResponse
// }

// func (a *EventsSubscriptionDocumentApiService) PutEventsSubsc(ctx context.Context, request *PutEventsSubscRequest) (*PutEventsSubscResponse, error) {
// 	var (
// 		localVarHTTPMethod   = strings.ToUpper("Put")
// 		localVarPostBody     interface{}
// 		localVarFormFileName string
// 		localVarFileName     string
// 		localVarFileBytes    []byte
// 		localVarReturnValue  PutEventsSubscResponse
// 	)

// 	// create path and map variables
// 	localVarPath := a.client.cfg.BasePath() + "/tsc-app-sessions/{appSessionId}/events-subscription"
// 	localVarPath = strings.Replace(localVarPath, "{"+"appSessionId"+"}", openapi.StringOfValue(*request.AppSessionId), -1)

// 	localVarHeaderParams := make(map[string]string)
// 	localVarQueryParams := url.Values{}
// 	localVarFormParams := url.Values{}

// 	localVarHTTPContentTypes := []string{"application/json"}

// 	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

// 	// to determine the Accept header
// 	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

// 	// set Accept header
// 	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
// 	if localVarHTTPHeaderAccept != "" {
// 		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
// 	}

// 	// body params
// 	localVarPostBody = request.EventsSubscReqData

// 	r, err := openapi.PrepareRequest(ctx, a.client.cfg, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
// 	if err != nil {
// 		return nil, err
// 	}

// 	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
// 	if err != nil || localVarHTTPResponse == nil {
// 		return nil, err
// 	}

// 	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
// 	if err != nil {
// 		return nil, err
// 	}
// 	err = localVarHTTPResponse.Body.Close()
// 	if err != nil {
// 		return nil, err
// 	}

// 	apiError := openapi.GenericOpenAPIError{
// 		RawBody:     localVarBody,
// 		ErrorStatus: localVarHTTPResponse.StatusCode,
// 	}

// 	switch localVarHTTPResponse.StatusCode {
// 	case 201:
// 		err = openapi.Deserialize(&localVarReturnValue.EventsSubscReqData, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		localVarReturnValue.Location = localVarHTTPResponse.Header.Get("Location")
// 		return &localVarReturnValue, nil
// 	case 200:
// 		err = openapi.Deserialize(&localVarReturnValue.EventsSubscReqData, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		return &localVarReturnValue, nil
// 	case 204:
// 		return &localVarReturnValue, nil
// 	case 307:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 308:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 400:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 401:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 403:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 404:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 411:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 413:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 415:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 429:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 500:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 502:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 503:
// 		var v PutEventsSubscError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	default:
// 		return nil, apiError
// 	}
// }

// // PutEventsSubscEventNotificationPostRequest
// type PutEventsSubscEventNotificationPostRequest struct {
// 	EventsNotification *models.EventsNotification
// }

// func (r *PutEventsSubscEventNotificationPostRequest) SetEventsNotification(EventsNotification models.EventsNotification) {
// 	r.EventsNotification = &EventsNotification
// }

// type PutEventsSubscEventNotificationPostResponse struct {
// }

// type PutEventsSubscEventNotificationPostError struct {
// 	Location             string
// 	Var3gppSbiTargetNfId string
// 	ProblemDetails       *models.ProblemDetails
// 	RedirectResponse     *models.RedirectResponse
// }

// func (a *EventsSubscriptionDocumentApiService) PutEventsSubscEventNotificationPost(ctx context.Context, uri string, request *PutEventsSubscEventNotificationPostRequest) (*PutEventsSubscEventNotificationPostResponse, error) {
// 	var (
// 		localVarHTTPMethod   = strings.ToUpper("Post")
// 		localVarPostBody     interface{}
// 		localVarFormFileName string
// 		localVarFileName     string
// 		localVarFileBytes    []byte
// 		localVarReturnValue  PutEventsSubscEventNotificationPostResponse
// 	)

// 	// create path and map variables
// 	localVarPath := uri

// 	localVarHeaderParams := make(map[string]string)
// 	localVarQueryParams := url.Values{}
// 	localVarFormParams := url.Values{}

// 	localVarHTTPContentTypes := []string{"application/json"}

// 	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

// 	// to determine the Accept header
// 	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

// 	// set Accept header
// 	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
// 	if localVarHTTPHeaderAccept != "" {
// 		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
// 	}

// 	// body params
// 	localVarPostBody = request.EventsNotification

// 	r, err := openapi.PrepareRequest(ctx, a.client.cfg, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
// 	if err != nil {
// 		return nil, err
// 	}

// 	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
// 	if err != nil || localVarHTTPResponse == nil {
// 		return nil, err
// 	}

// 	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
// 	if err != nil {
// 		return nil, err
// 	}
// 	err = localVarHTTPResponse.Body.Close()
// 	if err != nil {
// 		return nil, err
// 	}

// 	apiError := openapi.GenericOpenAPIError{
// 		RawBody:     localVarBody,
// 		ErrorStatus: localVarHTTPResponse.StatusCode,
// 	}

// 	switch localVarHTTPResponse.StatusCode {
// 	case 204:
// 		return &localVarReturnValue, nil
// 	case 307:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 308:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.RedirectResponse, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		v.Location = localVarHTTPResponse.Header.Get("Location")
// 		v.Var3gppSbiTargetNfId = localVarHTTPResponse.Header.Get("3gpp-Sbi-Target-Nf-Id")
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 400:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 401:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 403:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 404:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 411:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 413:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 415:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 429:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 500:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 502:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	case 503:
// 		var v PutEventsSubscEventNotificationPostError
// 		err = openapi.Deserialize(&v.ProblemDetails, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
// 		if err != nil {
// 			return nil, err
// 		}
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	default:
// 		var v PutEventsSubscEventNotificationPostError
// 		apiError.ErrorModel = v
// 		return nil, apiError
// 	}
// }
